language: node_js
node_js:
  - "0.10"
script:
  - npm install -g bower gulp
  - npm install
  - bower install
  - gulp build
  - wget -O rss.xml http://feeds.soundcloud.com/users/soundcloud:users:49720730/sounds.rss
  - cp index.html 404.html
  - rm .gitignore
  - rm -rf .git
  - git init
  - git config --global user.email "devminutes@gmail.com"
  - git config --global user.name "DevMinutes"
  - git remote add origin git@github.com:MilanLempera/milanlempera.github.io.git
  - git add .
  - git commit -m "New version"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master